<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Pool0Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pool0Repository extends EntityRepository
{
}
